//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPMSEntities1 : DbContext
    {
        public ERPMSEntities1()
            : base("name=ERPMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetail { get; set; }
        public virtual DbSet<SYS_用户信息表> SYS_用户信息表 { get; set; }
        public virtual DbSet<T_MIMS_材料编码表> T_MIMS_材料编码表 { get; set; }
        public virtual DbSet<T_MIMS_材料类别编码表> T_MIMS_材料类别编码表 { get; set; }
        public virtual DbSet<Table_岗位编码表> Table_岗位编码表 { get; set; }
        public virtual DbSet<T_EMMS_生产设备编码表> T_EMMS_生产设备编码表 { get; set; }
        public virtual DbSet<Table_组织编码表> Table_组织编码表 { get; set; }
        public virtual DbSet<T_FCMS_统计_供应商明细表> T_FCMS_统计_供应商明细表 { get; set; }
        public virtual DbSet<T_PHMS_统计_供应商明细表> T_PHMS_统计_供应商明细表 { get; set; }
    }
}
