//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public string CailiaoId { get; set; }
        public string CailiaoName { get; set; }
        public Nullable<int> Num { get; set; }
        public string MasterId { get; set; }
        public int Id { get; set; }
        public string 供应商编码 { get; set; }
        public string 材料名称 { get; set; }
        public Nullable<decimal> 总金额 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
    }
}
