//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_PHMS_统计_供应商明细表
    {
        public int ID { get; set; }
        [NotMapped()]
        public string 供应商编码 { get; set; }
        [NotMapped()]
        public string 入库单号 { get; set; }
        [NotMapped()]
        public string 订单号 { get; set; }
        [NotMapped()]
        public string 制单日期 { get; set; }
        [NotMapped()]
        public string 材料名称 { get; set; }
        [NotMapped()]
        public string 规格型号 { get; set; }
        [NotMapped()]
        public string 计量单位 { get; set; }
        [NotMapped()]
        public Nullable<int> 数量 { get; set; }
        [NotMapped()]
        public Nullable<decimal> 金额 { get; set; }
        [NotMapped()]
        public Nullable<decimal> 开票金额 { get; set; }
        [NotMapped()]
        public Nullable<decimal> 付款金额 { get; set; }

        
             [NotMapped()]
        public Nullable<decimal> Unit { get; set; }
    }
}
